# Build stage
FROM node:22-alpine AS build

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Build the app
RUN npm run build

FROM lipanski/docker-static-website:latest

# Copy your static files
COPY --from=build /app/dist .

EXPOSE 80