# Build stage
FROM node:22-alpine AS build

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Build the app
RUN npm run build

FROM pierrezemb/gostatic:latest

# Copy your static files
COPY --from=build /app/dist /srv/http

EXPOSE 8043